/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import java.awt.Color;
import java.awt.Image;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author chris
 */
public class JFrameInicio extends javax.swing.JFrame {

    private int nFiles = 188;
    private List<String> params;

    public JFrameInicio() {
        String rutaFrases = new File("frases.txt").getAbsolutePath();
        System.out.println(rutaFrases);
        
        String rutaParams = new File("params.txt").getAbsolutePath();
        System.out.println(rutaParams);
        
        setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
     
        initComponents();
        
        
        this.setLocationRelativeTo(null);
        
        List<String> frases = leerFrases(rutaFrases);
        params = leerFrases(rutaParams); // En este caso para iniciar parametros
        nFiles = Integer.parseInt(params.get(0));
        int r = Integer.parseInt(params.get(1));
        int g = Integer.parseInt(params.get(2));
        int b = Integer.parseInt(params.get(3));
        jLabelphrase.setForeground(new Color(r, g, b));
        System.out.println(params.toString());
        String fraseAleatoria = elegirFraseAleatoria(frases);
        //System.out.println("Frase aleatoria: " + fraseAleatoria);
        jLabelphrase.setText(fraseAleatoria);
        setImageLabel(jLabelWaifuImg, generarRandomImgSRC(nFiles));
    }

    private void setImageLabel(JLabel jlabel, String src) {
        ImageIcon image = new ImageIcon(src);
        int width = jlabel.getWidth();
        int height = jlabel.getHeight();
        int imageWidth = image.getIconWidth();
        int imageHeight = image.getIconHeight();
        double aspectRatio = (double) imageWidth / imageHeight;
        if (width / aspectRatio > height) {
            width = (int) (height * aspectRatio);
        } else {
            height = (int) (width / aspectRatio);
        }
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)
        );
        jlabel.setIcon(icon);
    }

    private String generarRandomImgSRC(int n) {
        Random random = new Random();
        int randomNumber = random.nextInt(n + 1);
        String src = new File("WaifusProgramming/"+ randomNumber + ".jpg").getAbsolutePath();
        System.out.println(src);
        return src;
    }

    private static List<String> leerFrases(String nombreArchivo) {
        List<String> frases = new ArrayList<>();
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(nombreArchivo), "UTF-8"));
            String line;
            while ((line = reader.readLine()) != null) {
                frases.add(line);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return frases;
    }

    private static String elegirFraseAleatoria(List<String> frases) {
        int indiceAleatorio = new Random().nextInt(frases.size());
        return frases.get(indiceAleatorio);
    }

    public int getnFiles() {
        return nFiles;
    }

    public List<String> getParams() {
        return params;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWaifuImg = new javax.swing.JLabel();
        jLabelphrase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabelWaifuImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWaifuImg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelWaifuImg.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabelphrase.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelphrase.setForeground(new java.awt.Color(153, 153, 255));
        jLabelphrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelphrase.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabelphrase, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabelWaifuImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelphrase, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelWaifuImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelWaifuImg;
    private javax.swing.JLabel jLabelphrase;
    // End of variables declaration//GEN-END:variables
}


/*
//Para renombrar imagenes
File folder = new File("ruta/al/directorio/de/imágenes");
        File[] listOfFiles = folder.listFiles();
        int count = 0;

        for (File file : listOfFiles) {
            if (file.isFile()) {
                String fileName = file.getName();
                String newFileName = count + fileName.substring(fileName.lastIndexOf("."));
                File newFile = new File("ruta/al/directorio/de/imágenes/" + newFileName);
                file.renameTo(newFile);
                count++;
            }
        }
 */

